### ISSUE TITLE
asciiText and asciiTextBody functions

### ISSUE THREAD

**Issue by chessai** [andrewthad/colonnade#10]
Would it make sense to have these, ie

```haskell
asciiText :: : Foldable f
  => Colonnade Headed a Text -- ^ columnar encoding
  -> f a -- ^ rows
  -> Text
asciiBody :: Foldable f
  => Colonnade (E.Sized Headed) a Text
  -> f a
  -> Text
```

If so, is it alright if I make a PR for them?

**Comment by chessai** [comment]
Unnecessary

**Comment by andrewthad** [comment]
To give a recap of our discussion for future viewers of this issue. The ascii table functions in `colonnade` are provided mostly as a way to use doctest. There implementations perform poorly and do not wrap wide data correctly. I am open to a `colonnade-ascii` package that implements a better version of the ascii table function. It might need to use [pretty](https://hackage.haskell.org/package/pretty-1.1.3.5) or one of its text-oriented derivatives to wrap cells properly.

**Comment by mckeankylej** [comment]
This is the correct package:
https://hackage.haskell.org/package/prettyprinter
